version: '3.8'
services:

  db:
    image: postgres:15-alpine
    volumes:
      - databasestore:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    volumes:
      - build_folder:/app/result_build/
    depends_on:
      - backend

  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9090"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address '0.0.0.0:9090'
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - build_folder:/usr/share/nginx/html/
      - static_value:/app/static/
      - media_value:/app/media/

    depends_on:
      - backend
      - frontend
      - minio

volumes:
  databasestore:
  static_value:
  media_value:
  build_folder:
  minio_data:
  minio_config:
